### ISSUE TITLE
Unable to change the address, once you set it the first time.

### ISSUE THREAD

**Issue by beargun** [Ghostbird/Arduino_EEPROM_RW#1]
Once setting the I2C address, using the `S` option has no effect. 

Steps to reproduce
  - type S80 to select address 80
  - type S81 to select address 81
  - address is however still set to 80

This is because typing `S` will call the `EEPROM_I2C_setAddress();` function, which will return the new address. However, nothing is done with the returned value.

Fix:
Change line 213 from `EEPROM_I2C_setAddress();` to `I2C_ADDRESS = EEPROM_I2C_setAddress();`

PS, thanks for the awesome tool. Though it took me quite some time to figure out this problem, as I though it was an hardware issue, instead of the software I was using to read (-:

**Comment by Ghostbird** [comment]
Fix has been merged. Thanks for the heads up.
Note that I do not have a test set-up available, so I'd be much obliged if you could verify the correctness of the fix. (I made a few extra, mainly cosmetic, changes.)

**Comment by beargun** [comment]
Everything is working perfectly. I have verified it with a 2kbit EEPROM and my logic analyzer.

Thanks for the fast fix.
